### ISSUE TITLE
Fix-1 version error (*.dll invalid!)

### ISSUE THREAD

**Issue by bullik01** [chr233/ASFEnhance#1]
`2021-06-27 11:09:52|ArchiSteamFarm-13715|ERROR|ASF|LoadAssembliesFrom() /root/ASF/plugins/ASFEnhance/ASFEnhance-fix-1.dll неверен!
2021-06-27 11:09:52|ArchiSteamFarm-13715|WARN|ASF|LoadAssembliesFrom() System.BadImageFormatException: Bad IL format. The format of the file '/root/ASF/plugins/ASFEnhance/ASFEnhance-fix-1.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
`

**Comment by bullik01** [comment]
Same result with non-fixed version:

`2021-06-27 11:13:15|ArchiSteamFarm-14473|ERROR|ASF|LoadAssembliesFrom() /root/ASF/plugins/ASFEnhance/ASFEnhance.dll неверен!
2021-06-27 11:13:15|ArchiSteamFarm-14473|WARN|ASF|LoadAssembliesFrom() System.BadImageFormatException: Bad IL format. The format of the file '/root/ASF/plugins/ASFEnhance/ASFEnhance.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
`

**Comment by chr233** [comment]
What's the version of the ASF you runing? The minimum version to use this plugin is 5.1.0.9, if you are using the old version, you need to compile yourself.

**Comment by bullik01** [comment]
ASF 5.1.0.9 - linux-x64

**Comment by chr233** [comment]
![image](https://user-images.githubusercontent.com/13798576/123544817-a1339080-d787-11eb-8e56-ed2bdc4dc46f.png)

I'm running ASF 5.1.0.9 on Ubuntu x64, all fine.

I have no idea about what cause this error.

**Comment by bullik01** [comment]
Maybe language or amout of bots? Or maybe something with file? I download it directly from github using "curl -O https://url"

**Comment by bullik01** [comment]
Additional question - you use generic or x64 version of ASF?

**Comment by chr233** [comment]
> Additional question - you use generic or x64 version of ASF?

Acctually ASF doesn't provide x86 version on windows or linux

**Comment by chr233** [comment]
> Maybe language or amout of bots? Or maybe something with file? I download it directly from github using "curl -O https://url"

I think you'd checck the file's size first

**Comment by bullik01** [comment]
I try and text you. Thanks for help!

**Comment by bullik01** [comment]
Downloaded by alt way - all good!
`2021-06-27 14:36:26|ArchiSteamFarm-21338|INFO|ASF|OnLoaded() ASFEnhance 1.5.2 Build 44
2021-06-27 14:36:26|ArchiSteamFarm-21338|INFO|ASF|OnLoaded() 作者 Chr_, 联系方式 chr@chrxw.com
2021-06-27 14:36:26|ArchiSteamFarm-21338|INFO|ASF|InitPlugins() ASFEnhance был успешно загружен!
`
