### ISSUE TITLE
Add a new command

### ISSUE THREAD

**Issue by aVitaliy** [chr233/ASFEnhance#101]
Hello.

Is it possible to create such a command.
Send from Bot1 to Bot2, for example, only 5 sets of cards from the CS:GO game or any other game. 
Craft these 5 sets on Bot2 to get a level 5 badge (this is already done by the CRAFTBADGE command).

I know ASF has a command !transfer@ Bot1 730 Bot2. But if there are a lot of such cards on Bot1, then it will just take a huge amount of time. Then again it is necessary to send all these cards to Bot3 and other BotXX in the same way.

But here commands to send only 5 sets of cards and not all cards would be a great solution to automate the process for crafting a badge on all Bots.

**Comment by chr233** [comment]
I had wrote another plugin for such card trade: https://github.com/chr233/CardTradeExtension

it can let you to transfer sets of card to other by given trade link

**Comment by aVitaliy** [comment]
I don't know but it doesn't work for me.

> `!FULLSET Bot1 730
<
CardTradeExtension 遇到错误, 日志如下
==========================================
 - 原始消息: FULLSET Bot1 730
 - Access: Owner
 - ASF 版本: 5.4.4.5
 - 插件版本: 1.0.3.1
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DisabledCmds": [
    "FOO",
    "BAR"
  ],
  "MaxItemPerTrade": 255
}
==========================================
 - 错误类型: System.MissingMethodException
 - 错误消息: Attempted to access a missing method.
   at CardTradeExtension.Card.Handler.GetAppCardGroup(Bot bot, IEnumerable`1 appIds, IEnumerable`1 inventory)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at CardTradeExtension.Card.Handler.GetAppCardGroup(Bot bot, IEnumerable`1 appIds, IEnumerable`1 inventory)
   at CardTradeExtension.Card.Command.ResponseFullSetCountOfGame(Bot bot, String query)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at CardTradeExtension.Card.Command.ResponseFullSetCountOfGame(String botNames, String query)
   at CardTradeExtension.CardTradeExtension.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
   at CardTradeExtension.CardTradeExtension.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamI`

**Comment by chr233** [comment]
I see, I'm working on it.
