### ISSUE TITLE
How to fix explorer?

### ISSUE THREAD

**Issue by ZamossIO** [chr233/ASFEnhance#127]
ASFenhance обнаружил ошибку, журнал ошибок ниже
==========================================
 - Origin Message: explorer zent2001
 - Access: Owner
 - Версия ASF: 5.4.7.3
 - Версия плагина: 1.8.6.2
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false,
  "DisabledCmds": [],
  "Address": null,
  "Addresses": []
}
==========================================
 - Exception Type: System.NullReferenceException
 - Exception Message: Object reference not set to an instance of an object.
   at ASFEnhance.Explorer.ReflectionHelper.GetPrivateField[T](Object instance, String fieldname)
   at ASFEnhance.Explorer.Command.ResponseExploreDiscoveryQueue(Bot bot, SemaphoreSlim semaphore)
   at ASFEnhance.Explorer.Command.ResponseExploreDiscoveryQueue(Bot bot, SemaphoreSlim semaphore)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Explorer.Command.ResponseExploreDiscoveryQueue(String botNames)
   at ASFEnhance.ASFEnhance.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
>

**Comment by chr233** [comment]
its ASF's function the command only reset the timer.
