### ISSUE TITLE
[BUG] CLAIMITEM

### ISSUE THREAD

**Issue by Romz24** [chr233/ASFEnhance#171]
**Describe the bug / Bug 描述**
When I enter the command `CLAIMITEM ASF` I get an error

**Error Log / 错误日志**
```txt
ASFenhance обнаружил ошибку, журнал ошибок ниже
==========================================================================
 - Origin Message: CLAIMITEM ASF
 - Access: Owner
 - Версия ASF: 5.5.0.0
 - Версия плагина: 2.0.1.3
==========================================================================
{
  "EULA": true,
  "Statistic": false,
  "DevFeature": false,
  "DisabledCmds": null,
  "Address": null,
  "Addresses": []
}
==========================================================================
 - Exception Type: System.MissingMethodException
 - Exception Message: Attempted to access a missing method.
   at ASFEnhance.Event.WebRequest.FetchToken(Bot bot)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFEnhance.Event.WebRequest.FetchToken(Bot bot)
   at ASFEnhance.Event.Command.ResponseClaimItem(Bot bot)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Event.Command.ResponseClaimItem(String botNames)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
```

**Comment by woctezuma** [comment]
> ASF: 5.5.0.0

👀

**Comment by chr233** [comment]
5.5.0.0 isn't a stable release yet, and it has many breaking changes, it takes time to make an adaptation

**Comment by chr233** [comment]
use 5.4.13.4 instead, to support 5.5.0.0 requires net8.0, and a lot work to do

**Comment by chr233** [comment]
uploaded 2.0.3.0 using ASF 5.5.0.0
