### ISSUE TITLE
ASFEnhance调用方法报错导致ASF报错退出

### ISSUE THREAD

**Issue by xduQuzhen** [chr233/ASFEnhance#180]
**Describe the bug / Bug 描述**
Describe what the bug is
简单描述一下是什么 bug

已将ASFEnhance更新至最新版本，加载了ASFEnhance的ASF在登录我的steam账号对应的机器人时，显示ASFEnhance调用了一个“ a missing method.”，随后ASF整个报错退出。删除ASFEnhance插件后，ASF不再报错。

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

未在ASF文件夹下下找到ASFEnhance日志，只找到了ASF的报错退出日志。
ASF版本：5.5.0.10 
ASFEnhance插件版本: 2.0.2.0 
以下是ASF的报错日志

```txt
2023-12-16 09:27:53|ArchiSteamFarm-9624|INFO|ASF|InitCore() ArchiSteamFarm V5.5.0.10 (win-x64/5c02e85f-06b4-4877-82c7-e082f430ad6f | .NET 8.0.0; win-x64; Microsoft Windows 10.0.19045)
2023-12-16 09:27:53|ArchiSteamFarm-9624|INFO|ASF|InitCore() Copyright © 2015-2023 JustArchiNET
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 正在初始化 Plugins……
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 正在加载 ASFEnhance V2.0.2.0……
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() ASFEnhance 加载成功！
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 正在加载 ItemsMatcherPlugin V5.5.0.10……
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() ItemsMatcherPlugin 加载成功！
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 正在加载 MobileAuthenticatorPlugin V5.5.0.10……
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() MobileAuthenticatorPlugin 加载成功！
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 正在加载 SteamTokenDumperPlugin V5.5.0.10……
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() SteamTokenDumperPlugin 加载成功！
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|InitPlugins() 您已将一个或多个自定义插件加载到 ASF 中。由于我们无法为修改过的程序提供支持，所以如果您遇到任何问题，请咨询相应插件的开发者。
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|UpdateAndRestart() ASF 将每隔 1 天自动检查新版本。
2023-12-16 09:27:54|ArchiSteamFarm-9624|INFO|ASF|Update() 正在检查新版本……
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|Update() 当前版本：5.5.0.10 | 最新版本：5.5.0.10
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|OnASFInit() 
==========================================================================
 █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗  
██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝  
██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
==========================================================================
ASFEnhance 版本 2.0.2.0
插件作者: Chr_, 联系方式: chr@chrxw.com
爱发电: https://afdian.net/@chr233
==========================================================================
未加载外部模块
==========================================================================
使用 "PLUGINVERSION [插件名]" / "PV [插件名]" 检查插件可用更新
使用 "PLUGINUPDATE [插件名]" / "PU [插件名]"  自动更新指定插件
不指定插件名时, 可为所有支持的插件检查更新 / 安装更新
==========================================================================

2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|Load() 正在加载 STD 全局缓存……
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|Load() 正在验证 STD 全局缓存完整性……
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|OnASFInit() SteamTokenDumperPlugin 加载成功，感谢您的帮助。首次提交将会在大约 16 分后开始。
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|StartInteractiveConsole() 交互式控制台已启用，输入 c 以进入命令模式。
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|Start() 正在启动 IPC 服务……
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:1242
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|Microsoft.Hosting.Lifetime|Content root path: D:\SoftWare\Tool\ASF-win-x64
2023-12-16 09:27:56|ArchiSteamFarm-9624|INFO|ASF|Start() IPC 服务已就绪！
2023-12-16 09:27:57|ArchiSteamFarm-9624|WARN|RU|InitStart() 您已在配置文件中禁用此机器人，该实例将不会启动！
2023-12-16 09:27:57|ArchiSteamFarm-9624|WARN|HK|InitStart() 您已在配置文件中禁用此机器人，该实例将不会启动！
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|小土|Start() 正在启动……
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|KOEI|Start() 正在启动……
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|KOEI|Connect() 正在连接……
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|驱真|Start() 正在启动……
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|小阿|Start() 正在启动……
2023-12-16 09:27:57|ArchiSteamFarm-9624|INFO|Lin|Start() 正在启动……
2023-12-16 09:28:02|ArchiSteamFarm-9624|INFO|KOEI|OnDisconnected() 已从 Steam 断开连接！
2023-12-16 09:28:07|ArchiSteamFarm-9624|INFO|小土|Connect() 正在连接……
2023-12-16 09:28:07|ArchiSteamFarm-9624|INFO|小土|OnConnected() 已连接到 Steam！
2023-12-16 09:28:07|ArchiSteamFarm-9624|INFO|小土|OnConnected() 登录中……
2023-12-16 09:28:08|ArchiSteamFarm-9624|INFO|KOEI|OnDisconnected() 重新连接中……
2023-12-16 09:28:08|ArchiSteamFarm-9624|INFO|小土|OnLoggedOn() 成功以 76561199278048714 的身份登录。
2023-12-16 09:28:08|ArchiSteamFarm-9624|INFO|小土|Init() 成功！
2023-12-16 09:28:08|ArchiSteamFarm-9624|DEBUG|小土|Refresh() 此机器人实例没有需要刷新的 App。
2023-12-16 09:28:09|ArchiSteamFarm-9624|INFO|小土|IsAnythingToFarm() 正在检查 Steam 徽章页面的第一页……
2023-12-16 09:28:11|ArchiSteamFarm-9624|INFO|小土|StartFarming() 该帐户已经无卡可挂！
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|Connect() 正在连接……
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|OnConnected() 已连接到 Steam！
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|OnConnected() 登录中……
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|OnLoggedOn() 成功以 76561198939713501 的身份登录。
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|Init() 成功！
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|IsAnythingToFarm() 正在检查 Steam 徽章页面的第一页……
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|Refresh() 正在获取共计 132 个 App Token……
2023-12-16 09:28:17|ArchiSteamFarm-9624|INFO|驱真|Refresh() 正在获取 132 个 App Token……
2023-12-16 09:28:18|ArchiSteamFarm-9624|INFO|驱真|Refresh() 已完成获取 132 个 App Token。
2023-12-16 09:28:18|ArchiSteamFarm-9624|INFO|驱真|Refresh() 已完成获取共计 132 个 App Token。
2023-12-16 09:28:18|ArchiSteamFarm-9624|INFO|驱真|Refresh() 正在获取共计 132 个 App 的所有 Depot……
2023-12-16 09:28:20|ArchiSteamFarm-9624|INFO|驱真|Refresh() 正在获取 132 个 App 的信息……
2023-12-16 09:28:20|ArchiSteamFarm-9624|INFO|驱真|IsAnythingToFarm() 正在检查其他徽章页面……
2023-12-16 09:28:20|ArchiSteamFarm-9624|INFO|驱真|Refresh() 已完成获取 132 个 App 的信息。
2023-12-16 09:28:22|ArchiSteamFarm-9624|INFO|驱真|StartFarming() 该帐户已经无卡可挂！
2023-12-16 09:28:26|ArchiSteamFarm-9624|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Attempted to access a missing method.
   at ASFEnhance.ASFEnhance.<>c__DisplayClass10_0.<<OnASFInit>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFEnhance.ASFEnhance.<>c__DisplayClass10_0.<OnASFInit>b__0(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__30_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean )
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2023-12-16 09:28:26|ArchiSteamFarm-9624|ERROR|ASF|Exit() 正在以非 0 错误代码退出！
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|Lin|Stop() 正在停止……
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|小土|Stop() 正在停止……
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|驱真|Stop() 正在停止……
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|小阿|Stop() 正在停止……
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|KOEI|Stop() 正在停止……
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|驱真|OnDisconnected() 已从 Steam 断开连接！
2023-12-16 09:28:26|ArchiSteamFarm-9624|INFO|小土|OnDisconnected() 已从 Steam 断开连接！

**Comment by chr233** [comment]
排查中

**Comment by Gensokyo1995** [comment]
ASF版本：5.5.0.10
ASFEnhance插件版本: 2.0.3.1
更新了插件最新版本还是同样的报错

**Comment by 1132647594** [comment]
ASF版本：5.5.0.10
ASFEnhance插件版本: 2.0.3.1
同楼上报错。本来以为是环境不对，更新了.NET 8.0还是报错，后面发现这个issue，删除插件后能正常使用。
![QQ图片20231216154156](https://github.com/chr233/ASFEnhance/assets/75550473/561abafa-240b-47c2-a051-2fc1195079e2)

**Comment by chr233** [comment]
> ASF版本：5.5.0.10 ASFEnhance插件版本: 2.0.3.1 同楼上报错。本来以为是环境不对，更新了.NET 8.0还是报错，后面发现这个issue，删除插件后能正常使用。 ![QQ图片20231216154156](https://private-user-images.githubusercontent.com/75550473/290979652-561abafa-240b-47c2-a051-2fc1195079e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTUwMjcsIm5iZiI6MTcwMjcxNDcyNywicGF0aCI6Ii83NTU1MDQ3My8yOTA5Nzk2NTItNTYxYWJhZmEtMjQwYi00N2MyLWEwNTEtMmZjMTE5NTA3OWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA4MTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjAyZmExNzVlMDQ4ODgzNDNlMWUyNDhjYTE0YmE1OTQxOWU2OWRjOGZmY2Q0NDQ5NTlmMDQ4NGVkODJiOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BeTUkk2ifxEQ-EIYdjsKmhUn_ZW2-DiH66-D7c8N4iA)

2.0.3.1 好像没有同步成最新的ASF，所以仍然不兼容，试试2.0.3.2，应该没问题

**Comment by chr233** [comment]
早上发布的 2.0.3.1 有点问题，换成 2.0.3.2 可解
