### ISSUE TITLE
command SETAVATAR not work

### ISSUE THREAD

**Issue by pushkinb** [chr233/ASFEnhance#215]
Hello, command SETAVATAR not work.

ASFenhance обнаружил ошибку, журнал ошибок ниже
==========================================================================
 - Origin Message: SETAVATAR https://gas-kvas.com/uploads/posts/2023-01/1673419348_gas-kvas-com-p-krasnie-risunki-anime-27.jpg
 - Access: Owner
 - Версия ASF: 5.5.2.3
 - Версия плагина: 2.0.12.1
==========================================================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false,
  "DisabledCmds": null,
  "Address": null,
  "Addresses": [],
  "ApiKey": null,
  "AutoClaimItemBotNames": null,
  "AutoClaimItemPeriod": 23
}
==========================================================================
 - Exception Type: System.MissingMethodException
 - Exception Message: Attempted to access a missing method.
   at ASFEnhance.Profile.WebRequest.ApplyCustomAvatar(Bot bot, String imgUrl)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFEnhance.Profile.WebRequest.ApplyCustomAvatar(Bot bot, String imgUrl)
   at ASFEnhance.Profile.Command.ResponseSetProfileAvatar(Bot bot, String imgUrl)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Profile.Command.ResponseSetProfileAvatar(String botNames, String imgUrl)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)

**Comment by chr233** [comment]
![image](https://github.com/chr233/ASFEnhance/assets/13798576/8f389774-1ca3-4b36-b85d-e0227c9d1ef7)

require generic version of ASF

**Comment by pushkinb** [comment]
oh bro, when i can download of right version?

**Comment by chr233** [comment]
> oh bro, when i can download of right version?
> 

![Screenshot_2024-02-19-08-07-28-252_com.github.android.jpg](https://github.com/chr233/ASFEnhance/assets/13798576/f8ed7e1c-bbbc-4bf6-94b0-035a89998c4e)
