### ISSUE TITLE
ASF 5.5.3.4 fails to start with ASFE 2.0.14.1

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#222]
log:
`2024-03-03 11:46:35|ArchiSteamFarm-1|INFO|ASF|InitCore() ArchiSteamFarm V5.5.3.4 (win-x64/4b1881ddf7cb457b83fd3ac5a049042c | .NET 8.0.1; win-x64; Microsoft Windows 10.0.19045) in [C:\ASF\TargetDirectory]
2024-03-03 11:46:36|ArchiSteamFarm-1|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-03-03 11:46:37|ArchiSteamFarm-1|INFO|ASF|Update() Checking for new version...
2024-03-03 11:46:37|ArchiSteamFarm-1|WARN|ASF|Load() Your IPC password seems to be weak. Consider choosing a stronger one for increased security. Details: Add another word or two.  Uncommon words are better.
2024-03-03 11:46:38|ArchiSteamFarm-1|INFO|ASF|Update() Local version: 5.5.3.4 | Remote version: 6.0.0.3
2024-03-03 11:46:38|ArchiSteamFarm-1|INFO|ASF|Update() New ASF version is available! Consider updating yourself!
2024-03-03 11:46:43|ArchiSteamFarm-1|ERROR|ASF|LoadAssembliesFrom() C:\ASF\TargetDirectory\plugins\System.Composition.AttributedModel.dll is invalid!
2024-03-03 11:46:43|ArchiSteamFarm-1|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-03-03 11:46:44|ArchiSteamFarm-1|INFO|ASF|InitPlugins() Initializing Plugins...
2024-03-03 11:46:44|ArchiSteamFarm-1|ERROR|ASF|InitPlugins() System.MissingMethodException: Attempted to access a missing method.
   at System.RuntimeMethodHandle.IsCAVisibleFromDecoratedType(QCallTypeHandle, RuntimeMethodHandleInternal, QCallTypeHandle, QCallModule)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo, RuntimeType)
   at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Type, Boolean)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo, Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttributes[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.DiscoverPropertyExports(TypeInfo partType)+MoveNext()
   at System.Composition.TypedParts.Discovery.TypeInspector.DiscoverExports(TypeInfo partType)+MoveNext()
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
2024-03-03 11:46:54|ArchiSteamFarm-1|ERROR|ASF|Exit() Exiting with 1 error code!`

too many files in ASFEnhance-en-US.zip?
![image](https://github.com/chr233/ASFEnhance/assets/28785698/c8884ceb-b839-4030-a062-b2cd56e65234)

**Comment by chr233** [comment]
lol， try delete these dlls except the ASFEnhance.dll

**Comment by Botan626** [comment]
> lol， try delete these dlls except the ASFEnhance.dll

didn't help

**Comment by aq5ucc9nuih** [comment]
Same problem

**Comment by aq5ucc9nuih** [comment]
And [ASFEnhance 2.0.13.2] started well, but not the [E 2.0.14.1]
#

**Comment by Botan626** [comment]
still lots of files in ASFEnhance 2.0.14.2
install them all?
![image](https://github.com/chr233/ASFEnhance/assets/28785698/44dba6ee-f8c3-43c1-a3fa-e9120796d887)

**Comment by chr233** [comment]
> still lots of files in ASFEnhance 2.0.14.2 en-US zip install them all? ![image](https://private-user-images.githubusercontent.com/28785698/310025888-44dba6ee-f8c3-43c1-a3fa-e9120796d887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzA2OTAsIm5iZiI6MTcwOTYzMDM5MCwicGF0aCI6Ii8yODc4NTY5OC8zMTAwMjU4ODgtNDRkYmE2ZWUtZjhjMy00M2MxLWEzZmEtZTkxMjA3OTZkODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5MTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMjYyZjcwYzYxNjdkZDYwMmE4ZjdjMzRhM2E2YjNkZDNkZWZhMmM0MmE0OTExYjMzNjM1ZDI4YzQ3OWFiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YfYsg6OeJNQSLGpqOXaOs_KjGRBd30qt6ZqpS6WJqb8)

only ASFEnhance.dll is enougth

**Comment by Botan626** [comment]
> only ASFEnhance.dll is enougth

now it works, but I installed ASFE from en-US zip and it's not english

![image](https://github.com/chr233/ASFEnhance/assets/28785698/467707b0-1366-4749-ab34-73e425673b3a)

**Comment by chr233** [comment]
> > only ASFEnhance.dll is enougth
> 
> now it works, but I installed ASFE from en-US zip and it's not english
> 
> ![image](https://private-user-images.githubusercontent.com/28785698/310064437-467707b0-1366-4749-ab34-73e425673b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTAyMTMsIm5iZiI6MTcwOTY4OTkxMywicGF0aCI6Ii8yODc4NTY5OC8zMTAwNjQ0MzctNDY3NzA3YjAtMTM2Ni00NzQ5LWFiMzQtNzNlNDI1NjczYjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAxNTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2M5ZTk1YjAyZTM1MDk4ZDgxZDMwNDYwYTQzYWI2ZjE5NjljOGE0NDMwMDk1M2Y5NTE5MzMzYjk0OGUwZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qF0TMKhf-3zH0mUiYZBErwzv7EaxoQMrlPqOXGIZHrk) and here ![image](https://private-user-images.githubusercontent.com/28785698/310064836-f668c4ee-e923-435d-a47e-c160b83126e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTAyMTMsIm5iZiI6MTcwOTY4OTkxMywicGF0aCI6Ii8yODc4NTY5OC8zMTAwNjQ4MzYtZjY2OGM0ZWUtZTkyMy00MzVkLWE0N2UtYzE2MGI4MzEyNmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAxNTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NDg2Yjg2MDc2YzhhZDkzNGVlNGZkZmRiZjMxMzk2NmM1M2ZiMGFkOTIwZTZiYzIxNDMwNjI0YmQ0N2RlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TKKjafCVOcMX1wPYJ__ivBQzikgXTusdW6Za3sjvioI)

These texts have not been translated yet, you can update translation here https://crowdin.com/project/asfenhance

**Comment by Botan626** [comment]
> These texts have not been translated yet, you can update translation here https://crowdin.com/project/asfenhance

I don't know chinese, so I can't translate.
