### ISSUE TITLE
2.0.15.0 error

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#225]
Again lots of files in zip!
![image](https://github.com/chr233/ASFEnhance/assets/28785698/9f64a887-b5cc-42ce-a6d3-14069fb3547a)

and ASF error after update:
`2024-03-08 17:41:15|ArchiSteamFarm-1|INFO|ASF|Update() Local version: 5.5.3.4 | Remote version: 6.0.0.3
2024-03-08 17:41:15|ArchiSteamFarm-1|INFO|ASF|Update() New ASF version is available! Consider updating yourself!
2024-03-08 17:41:20|ArchiSteamFarm-1|ERROR|ASF|LoadAssembliesFrom() C:\ASF\TargetDirectory\plugins\System.Composition.AttributedModel.dll is invalid!
2024-03-08 17:41:20|ArchiSteamFarm-1|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)`

**Comment by Msearla** [comment]
我使用最新版asfV6.0.0.3时也遇到了报错，与之类似，是否最新版asfe2.0.15.0并不支持asf6.0.0.3

**Comment by chr233** [comment]
> 我使用最新版asfV6.0.0.3时也遇到了报错，与之类似，是否最新版asfe2.0.15.0并不支持asf6.0.0.3

6.0.0.x请使用2.1.0.0

**Comment by chr233** [comment]
> > 我使用最新版asfV6.0.0.3时也遇到了报错，与之类似，是否最新版asfe2.0.15.0并不支持asf6.0.0.3
> 
> 6.0.0.x请使用2.1.0.0

2.1.0.0 中不包含最近2个版本中更新的购物车功能，得等我出院了才能更新，明天要住院动手术

**Comment by guihkx** [comment]
Hi,

ASFEnhance 2.0.16.2 still doesn't load with ASF 6.0.3:

```
2024-03-09 14:46:37|ArchiSteamFarm-33287|ERROR|ASF|InitPlugins() Failed due to error: ASFEnhance, Version=2.0.16.2, Culture=neutral, PublicKeyToken=null
2024-03-09 14:46:37|ArchiSteamFarm-33287|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'OnASFInit' in type 'ASFEnhance.ASFEnhance' from assembly 'ASFEnhance, Version=2.0.16.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Method 'OnASFInit' in type 'ASFEnhance.ASFEnhance' from assembly 'ASFEnhance, Version=2.0.16.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

From the release notes of [ASF 6.0.0.3](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/6.0.0.3): 

> Changes for plugin creators:
>
>`OnASFInit()` and `OnBotInitModules()` found in `IASF` and `IBotModules` plugin interfaces have changed the signature of `additionalConfigProperties` from `JToken` to `JsonElement`. If you're not using additional config props, change in signature is sufficient, otherwise, you'll need to correct existing usage a bit to the new API.

It looks like you're still using the old signature:

https://github.com/chr233/ASFEnhance/blob/b20820d2110c75ecbe25c199d7b45fda27f14bbb/ASFEnhance/ASFEnhance.cs#L32

**Comment by chr233** [comment]
use 2.1.1.0, now ASFEnhance support 6.0.0.3
