### ISSUE TITLE
Method not found on OS-specific versions of ASF

### ISSUE THREAD

**Issue by shinji257** [chr233/ASFEnhance#228]
**Describe the bug / Bug 描述**
When running ASFEnhance on OS-specific builds of ASF 6.0.0.3 a Method not found error is generated during startup.

**Error Log / 错误日志**
```
2024-03-10 00:57:07|ArchiSteamFarm-18|ERROR|ASF|OnASFInitModules() System.TypeInitializationException: The type initializer for 'ASFEnhance.Utils' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void System.Text.Json.JsonSerializerOptions.set_NumberHandling(System.Text.Json.Serialization.JsonNumberHandling)'.
   --- End of inner exception stack trace ---
   at ASFEnhance.Utils.set_Config(PluginConfig value)
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass12_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
```

```txt
ASFenhance 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 6.0.0.3
 - 插件版本: 2.1.1.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
--> System.MissingMethodException: Method not found: 'Void System.Text.Json.JsonSerializerOptions.set_NumberHandling(System.Text.Json.Serialization.JsonNumberHandling)'.
   --- End of inner exception stack trace ---
   at ASFEnhance.Utils.set_Config(PluginConfig value)
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass12_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
```

Additional information: I run ASF using a docker container so it isn't possible for me to use the generic version in my current setup.  ASF author recommends using OS specific builds rather than using the generic one.

**Comment by chr233** [comment]
fix in 2.1.1.1

**Comment by chr233** [comment]
![IMG_20240310_150459.jpg](https://github.com/chr233/ASFEnhance/assets/13798576/0b5497e6-6be6-4cef-bfcb-3c7a95688423)

in the hosptial right now

**Comment by guihkx** [comment]
Bro is bedridden and still managing to fix bugs and make new a release!

Seriously though, I wish you a speedy recovery.

**Comment by Domjul** [comment]
I wish you a speedy recovery and all the best too! 💐

**Comment by shinji257** [comment]
You didn't have to fix it that quickly!  Take care of yourself first and we can wait until you recover. ;)

**Comment by chr233** [comment]
> You didn't have to fix it that quickly!  Take care of yourself first and we can wait until you recover. ;)

2.1.1.1 fix this

**Comment by chr233** [comment]
> Bro is bed-rest and still managing to fix bugs and make new a release!
> 
> Seriously though, I wish you a speedy recovery.

lol, just have some issues with my ass

**Comment by shinji257** [comment]
> > You didn't have to fix it that quickly!  Take care of yourself first and we can wait until you recover. ;)
> 
> 2.1.1.1 fix this

Yes I saw.  Thank you.  Can confirm fixed.  Will close this now.
