### ISSUE TITLE
Removedemos command does not work

### ISSUE THREAD

**Issue by wolerine** [chr233/ASFEnhance#243]
**Describe the bug / Bug 描述**
Describe what the bug is
Removedemos command returns following error.
Also same error with  2.1.2.3 too

**Error Log / 错误日志**

```txt
 ASFenhance encountered error, error logs below
==========================================================================
 - Origin Message: removedemos
 - Access: Owner
 - ASF Version: 6.0.1.16
 - Plugin Version: 2.1.2.4
==========================================================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false,
  "DisabledCmds": null,
  "Address": null,
  "Addresses": [],
  "ApiKey": null,
  "AutoClaimItemBotNames": "w0lerine",
  "AutoClaimItemPeriod": 23
}
==========================================================================
 - Exception Type: System.MissingMethodException
 - Exception Message: Method not found: 'System.Range System.Range.StartAt(System.Index)'.
   at ASFEnhance.Account.HtmlParser.ParseLincensesPage(HtmlDocumentResponse response)
   at ASFEnhance.Account.WebRequest.GetOwnedLicenses(Bot bot)
   at ASFEnhance.Account.Command.ResponseRemoveAllDemos(Bot bot)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
```

**Comment by chr233** [comment]
looks like require generic version*s asf

**Comment by wolerine** [comment]
switch to generic version worked
thank you
