### ISSUE TITLE
Error when starting ASF

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#264]
ASFEnhance v2.1.6.0 is installed.

```
2024-06-11 15:17:38|ArchiSteamFarm-1|INFO|ASF|InitPlugins() ASFEnhance/ASFEnhance plugin has been registered and enabled for automatic updates.
2024-06-11 15:17:38|ArchiSteamFarm-1|WARN|ASF|InitPlugins() Custom plugins have been registered for automatic updates. ASF team would like to remind you that, for your own safety, you should enable automatic updates only from trusted parties. If you didn't intend to do this, you can disable plugin updates in ASF global config.
2024-06-11 15:17:38|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Checking for new version...
2024-06-11 15:17:39|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Local version: 6.0.4.0 | Remote version: 6.0.4.0
2024-06-11 15:17:39|ArchiSteamFarm-1|INFO|ASF|UpdatePlugins() Checking for plugin updates...
2024-06-11 15:17:39|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for ASFEnhance plugin...
2024-06-11 15:17:40|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() New ASFEnhance plugin version is available! Consider updating yourself!
2024-06-11 15:17:40|ArchiSteamFarm-1|INFO|ASF|Load() Loading STD global cache...
2024-06-11 15:17:40|ArchiSteamFarm-1|ERROR|ASF|OnASFInitModules() System.TypeLoadException
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass16_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
2024-06-11 15:17:40|ArchiSteamFarm-1|INFO|ASF|Load() Validating STD global cache integrity...
```

**Comment by Botan626** [comment]
same error with ASF 6.0.4.1 and ASFE 2.1.8.1

**Comment by chr233** [comment]
use ASF 6.0.3.4

**Comment by chr233** [comment]
https://github.com/chr233/ASFEnhance/releases/tag/2.1.10.0

2.1.10.0 supported ASF 6.0.4.4

**Comment by Botan626** [comment]
> 2.1.10.0 supported ASF 6.0.4.4

not fixed same error

**Comment by chr233** [comment]
> > 2.1.10.0 supported ASF 6.0.4.4
> 
> not fixed same error

pls update your ASF to 6.0.4.4

**Comment by Botan626** [comment]
> pls update your ASF to 6.0.4.4

My ASF is ASF 6.0.4.4 - win-x64 and there is this error.

**Comment by chr233** [comment]
2.1.10.1 maybe fixed

**Comment by Botan626** [comment]
> 2.1.10.1 maybe fixed

fixed
