### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by stickerx** [chr233/ASFEnhance#275]
2024-07-01 03:15:27|ArchiSteamFarm-3076|INFO|ASF|InitCore() ArchiSteamFarm V6.0.3.3 (win-x64/b33cbe9373b048cbaf19c2ff07731ed9 | .NET 8.0.6; win-x64; Microsoft Windows 6.1.7601 Service Pack 1) in [C:\Users\Jeow\Desktop\ASF]
2024-07-01 03:15:27|ArchiSteamFarm-3076|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-07-01 03:15:28|ArchiSteamFarm-3076|WARN|ASF|InitGlobalConfigAndLanguage() config\ASF.json config file will be migrated to the latest syntax...
2024-07-01 03:15:28|ArchiSteamFarm-3076|INFO|ASF|InitGlobalConfigAndLanguage() Done!
2024-07-01 03:15:31|ArchiSteamFarm-3076|INFO|ASF|InitPlugins() Initializing Plugins...
2024-07-01 03:15:31|ArchiSteamFarm-3076|ERROR|ASF|InitPlugins() Failed due to error: ASFEnhance, Version=2.1.9.2, Culture=neutral, PublicKeyToken=null
2024-07-01 03:15:31|ArchiSteamFarm-3076|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
System.IO.FileNotFoundException: 
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
File name: 'ArchiSteamFarm, Version=6.0.3.4, Culture=neutral, PublicKeyToken=504f46588cc351a9'
2024-07-01 03:15:41|ArchiSteamFarm-3076|ERROR|ASF|Exit() Exiting with 1 error code!

**Comment by chr233** [comment]
use asf 6.0.3.4 will fix this

**Comment by VladozPlay** [comment]
2024-07-01 21:34:59|ArchiSteamFarm-16664|ERROR|ASF|OnASFInitModules() System.TypeLoadException
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass16_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
   
   ASFEnhance, Version=2.1.9.2,
   ArchiSteamFarm V6.0.4.4

**Comment by chr233** [comment]
> 2024-07-01 21:34:59|ArchiSteamFarm-16664|ERROR|ASF|OnASFInitModules() System.TypeLoadException at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties) at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass16_0.<OnASFInitModules>b__0(IASF plugin) at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() at System.Threading.Tasks.Task.WhenAll(IEnumerable`1) at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks) at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
> 
> ASFEnhance, Version=2.1.9.2 ArchiSteamFarm V6.0.4.4

use ASFEnhance 2.1.10.3
