### ISSUE TITLE
group commands error

### ISSUE THREAD

**Issue by klNuno** [chr233/ASFEnhance#28]
Hello, `JOINGROUP` and `GROUPLIST` doesn't work, I get this everytime I run one of them :

```
ASFenhance encountered error, error logs below
==========================================
- Origin Message: gl asf
- Access: Owner
- ASF Version: 5.2.7.7
- Plugin Version: 1.6.8.661
==========================================
null
==========================================
- Exception Type: System.NullReferenceException
- Exception Message: Object reference not set to an instance of an object.
at ASFEnhance.ASFEnhance.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
```

**Comment by chr233** [comment]
can you give me your bot's steamid64? I'm unable to reproduce

**Comment by klNuno** [comment]
Sorry for the wait,
It happens for every account I have, no matter what I write. one of the accounts : 76561199009662934

**Comment by klNuno** [comment]
just checked it is set

**Comment by maplepy** [comment]
how is it completed without a fix?N

**Comment by chr233** [comment]
Already fixed
