### ISSUE TITLE
[Bug] Error while purchasing games, but it works.

### ISSUE THREAD

**Issue by TheRhanderson** [chr233/ASFEnhance#29]
When purchasing games, the plugin executes requests successfully, purchasing all games without any problem. However, the log does not return a confirmation message, but another error. It doesn't impact how the plugin works once the games are purchased, but it's a bug you might be interested in looking at later.

```
 - Exception Type: System.MissingMethodException
 - Exception Message: Method not found: 'System.Collections.Generic.IEnumerable`1<AngleSharp.Dom.IElement> ArchiSteamFarm.Core.Utilities.SelectNodes(AngleSharp.Dom.IDocument, System.String)'.
   at ASFEnhance.Cart.HtmlParser.ParseCartPage(HtmlDocumentResponse response)
   at ASFEnhance.Cart.WebRequest.ClearCart(Bot bot)
   at ASFEnhance.Cart.Command.ResponsePurchaseSelf(Bot bot)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Cart.Command.ResponsePurchaseSelf(String botNames)
   at ASFEnhance.ASFEnhance.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
```

Running ASF 5.3.0.1 and latest version of ASFEnhance.

**Comment by chr233** [comment]
Please use ASF 5.2.8.4 instead, ASF had change its html parser API in 5.3.x.x, I will not update ASF's version till ASF published its stable release.

Or you can fork this repo, and complie with the latest ASF yourself

**Comment by TheRhanderson** [comment]
Oh okay. So you are aware and just waiting. That's what I needed to know. Thanks.
