### ISSUE TITLE
ASF V6.0.5.2插件运行报错

### ISSUE THREAD

**Issue by Gensokyo1995** [chr233/ASFEnhance#302]
**Describe the bug / Bug 描述**
Describe what the bug is
ASF V6.0.5.2版本 插件运行报错

**Error Log / 错误日志**
ASFenhance 遇到错误, 日志如下
==========================================
 - ASF 版本:  V6.0.5.2
 - 插件版本: V2.1.12.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
2024-08-02 20:47:35|ArchiSteamFarm-17340|ERROR|ASF|OnASFInit() System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement, JsonSerializerOptions )
   at ASFAchievementManagerEx.ASFAchievementManagerEx.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
2024-08-02 20:47:35|ArchiSteamFarm-17340|WARN|ASF|OnASFInit() 
==========================================
ASF Achievemenevement Manager Ex: 尚未同意 ASFEnhance.EULA, 部分命令已禁用
==========================================

2024-08-02 20:47:35|ArchiSteamFarm-17340|INFO|ASF|OnASFInit() 
==========================================================================
 █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗  
██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝  
██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
==========================================================================
ASFEnhance 版本 2.1.12.0
插件作者: Chr_, 联系方式: chr@chrxw.com
爱发电: https://afdian.net/@chr233
==========================================================================
已加载 1 个外部模块

1: [AAM] ASF Achievemenevement Manager Ex 1.1.0.1
==========================================================================

2024-08-02 20:47:35|ArchiSteamFarm-17340|ERROR|ASF|OnASFInit() System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement, JsonSerializerOptions )
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)

**Comment by chr233** [comment]
换6.0.4.4，只适配稳定版

**Comment by Gensokyo1995** [comment]
> 换6.0.4.4，只适配稳定版

ASF已更新V6.0.5.2
![image](https://github.com/user-attachments/assets/4464a768-8de1-4c5d-8099-a1f00dafd755)

**Comment by Botan626** [comment]
not fixed in ASFEnhance 2.2.0.0 with ASF 6.0.5.2

```
2024-08-03 13:07:41|ArchiSteamFarm-15652|INFO|ASF|UpdatePlugins() Checking for plugin updates...
2024-08-03 13:07:41|ArchiSteamFarm-15652|INFO|ASF|UpdatePlugin() Checking update for ASFEnhance plugin...
2024-08-03 13:07:42|ArchiSteamFarm-15652|INFO|ASF|GetTargetReleaseURL() No update available for ASFEnhance plugin: 2.2.0.0 ≥ 2.2.0.0.
2024-08-03 13:07:42|ArchiSteamFarm-15652|INFO|ASF|Load() Loading STD global cache...
2024-08-03 13:07:42|ArchiSteamFarm-15652|INFO|ASF|OnASFInit()
==========================================================================
 █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗
██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝
██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
==========================================================================
ASFEnhance Version 2.2.0.0
Developed by Chr_, email chr@chrxw.com
Donate: https://afdian.com/@chr233
==========================================================================
Submodule not loaded
==========================================================================

2024-08-03 13:07:42|ArchiSteamFarm-15652|INFO|ASF|Load() Validating STD global cache integrity...
2024-08-03 13:07:42|ArchiSteamFarm-15652|INFO|ASF|OnASFInit() SteamTokenDumperPlugin is currently disabled according to your configuration. If you'd like to help SteamDB in data submission, please check out our wiki.
2024-08-03 13:07:42|ArchiSteamFarm-15652|ERROR|ASF|OnASFInit() System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement, JsonSerializerOptions )
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
```

**Comment by JustArchi** [comment]
@chr233 replacing your custom `JsonSerializer` calls with ASF helpers from https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/ArchiSteamFarm/Helpers/Json/JsonUtilities.cs should do the trick.

`JsonSerializer.Serialize` -> `ToJsonText()`
`JsonSerializer.Deserialize` -> `ToJsonObject<T>()`

**Comment by chr233** [comment]
thank you

**Comment by Gensokyo1995** [comment]
测试了下ASFEnhance没报错了，我还使用了ASFAchievementManagerEx插件，这个还在报错

**Comment by chr233** [comment]
> 测试了下ASFEnhance没报错了，我还使用了ASFAchievementManagerEx插件，这个还在报错

有空更新，最近比较忙
