### ISSUE TITLE
Init fail in ASF v6.0.6.1

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#304]
ASF v6.0.6.1 can't start with ASFE v2.2.0.1.

```
2024-08-06 15:43:03|ArchiSteamFarm-10556|INFO|ASF|InitCore() ArchiSteamFarm V6.0.6.1 (win-x64/7807b9f72c9841a3888ecfa7d8a2a2a1 | .NET 8.0.7; win-x64; Microsoft Windows 10.0.19045) in [C:\ASF\TargetDirectory]
2024-08-06 15:43:03|ArchiSteamFarm-10556|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-08-06 15:43:05|ArchiSteamFarm-10556|INFO|ASF|InitPlugins() Initializing Plugins...
2024-08-06 15:43:05|ArchiSteamFarm-10556|ERROR|ASF|InitPlugins() System.TypeLoadException
   at System.ModuleHandle.ResolveType(QCallModule, Int32, IntPtr*, Int32, IntPtr*, Int32, ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
```

**Comment by chr233** [comment]
asfenhance 2.2.0.1 only support asf 6.0.5.2
