### ISSUE TITLE
取消关注所有鉴赏家报错

### ISSUE THREAD

**Issue by gyq180** [chr233/ASFEnhance#305]
**Describe the bug / Bug 描述**
取消关注所有鉴赏家报错

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

```txt
ASFenhance 遇到错误, 日志如下
==========================================================================
 - 原始消息: UFACU 1
 - Access: Owner
 - ASF 版本: 6.0.5.2
 - 插件版本: 2.2.0.1
==========================================================================
{"EULA":true,"Statistic":true,"DevFeature":false,"DisabledCmds":null,"Address":null,"Addresses":[],"ApiKey":null,"AutoClaimItemBotNames":null,"AutoClaimItemPeriod":23,"DefaultLanguage":null,"CustomGifteeMessage":null}
==========================================================================
 - 错误类型: System.FormatException
 - 错误消息: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1)
   at System.UInt64.Parse(String s, NumberStyles style, IFormatProvider provider)
   at ASFEnhance.Curator.Command.<>c__DisplayClass5_0.<<ResponseUnFollowAllCurators>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at ASFEnhance.Curator.Command.ResponseUnFollowAllCurators(Bot bot)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Curator.Command.ResponseUnFollowAllCurators(String botNames)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)

**Comment by chr233** [comment]
2.2.1.1 已修复
