### ISSUE TITLE
Inaccurate update logic (latest ASFE version updating itself)

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#324]
During updating ASF from v6.0.7.5 to v6.0.8.0 ASFEnhance was updated from v2.2.3.3 to v2.2.3.3.

```
2024-10-01 00:43:31|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Local version: 6.0.7.5 | Remote version: 6.0.8.0
2024-10-01 00:43:31|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Fetching checksum from the remote server...
2024-10-01 00:43:32|ArchiSteamFarm-1|INFO|ASF|UpdateASF() This is automated GitHub deployment, human-readable changelog should be available soon. In the meantime please refer to GitHub commits.

2024-10-01 00:43:32|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Downloading new version: 6.0.8.0 (18 MB)... While waiting, consider donating if you appreciate the work being done! :)
2024-10-01 00:43:33|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 0%...
2024-10-01 00:43:35|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 10%...
2024-10-01 00:43:36|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 20%...
2024-10-01 00:43:37|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 30%...
2024-10-01 00:43:38|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 40%...
2024-10-01 00:43:38|ArchiSteamFarm-1|INFO|03|FarmHours() Still farming: 262280
2024-10-01 00:43:39|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 50%...
2024-10-01 00:43:40|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 60%...
2024-10-01 00:43:40|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 70%...
2024-10-01 00:43:41|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 80%...
2024-10-01 00:43:42|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 90%...
2024-10-01 00:43:43|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASF-win-x64.zip 100%...
2024-10-01 00:43:43|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Verifying checksum of the downloaded binary against the one from the remote server...
2024-10-01 00:43:43|ArchiSteamFarm-1|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Patching ASF files...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdatePlugins() Checking for plugin updates...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for ASFAchievementManager plugin...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for ASFEnhance plugin...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for CommandAliasPlugin plugin...
2024-10-01 00:44:14|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for CommandlessRedeem plugin...
2024-10-01 00:44:15|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() No update available for ASFAchievementManager plugin: 1.0.0.1 ≥ 1.0.0.1.
2024-10-01 00:44:15|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() Found ASFEnhance plugin update from version 2.2.3.3 to 2.2.3.3...
2024-10-01 00:44:15|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Updating ASFEnhance plugin...
2024-10-01 00:44:15|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() No update available for CommandAliasPlugin plugin: 1.0.0.2 ≥ 1.0.0.2.
2024-10-01 00:44:15|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() No update available for CommandlessRedeem plugin: 1.0.0.0 ≥ 1.0.0.0.
2024-10-01 00:44:16|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASFEnhance 0%...
2024-10-01 00:44:17|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Patching ASF files...
2024-10-01 00:44:17|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Updating ASFEnhance plugin has succeeded, the changes will be loaded on the next ASF launch.
2024-10-01 00:44:21|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Update process finished!
```

**Comment by Botan626** [comment]
maybe updating logic from @Rudokhvist will help you to solve this

https://github.com/CatPoweredPlugins/CommandAliasPlugin/blob/main/CommandAliasPlugin/CommandAliasPlugin.cs

**Comment by JustArchi** [comment]
Not an issue with ASFE - ASF for compatibility reasons will update the plugin to the same version if more than one zip asset is found, since new ASF version could decide to use different asset than the one used in the previous run.

I have no clue why ASFE provides a zip asset per language though :slightly_smiling_face:

**Comment by Botan626** [comment]
> I have no clue why ASFE provides a zip asset per language though 🙂

So having only single ASFEnhance.zip archive in ASFE releases would fix it?

**Comment by JustArchi** [comment]
Yes, although what you're describing is not an issue, plugin can force itself to be updated to the same version at any time it wants, and it should never cause you issues.

**Comment by Botan626** [comment]
> plugin can force itself to be updated to the same version at any time it wants

I'm pretty sure @chr233 never intended this.

**Comment by Botan626** [comment]
> since new ASF version could decide to use different asset

And if the asset ASF decided to update to is the same as current one why updating?

In this case ASFE is in `ASFEnhance-en-US` directory (asset name?), version is the same (2.2.3.3), why updating?

**Comment by chr233** [comment]
> Not an issue with ASFE - ASF for compatibility reasons will update the plugin to the same version if more than one zip asset is found, since new ASF version could decide to use different asset than the one used in the previous run.
> 
> I have no clue why ASFE provides a zip asset per language though 🙂

tried use resx for multiple language support, and it will output resource dlls like `zh-hans/ASFEnhance.resources.dll`, and the plugin will always use the default language, even if define a linguage in String.Format method (tested in ASF 5.x.x.x), so I decide to use this way, not elegant enough, but it works

**Comment by JustArchi** [comment]
All ASF plugins are shipped with multi-lang support and they work fine, so it seems ASFE does something different which is why it doesn't load.

**Comment by chr233** [comment]
> All ASF plugins are shipped with multi-lang support and they work fine, so it seems ASFE does something different which is why it doesn't load. You definitely should not have a real need for that.

You are right, this's a "historical issues"

**Comment by chr233** [comment]
> Now ASFE updates to v2.2.4.2.
> 
> 2024-10-07 22:13:33|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() Found ASFEnhance plugin update from version 2.2.4.0 to 2.2.4.2... 2024-10-07 22:18:17|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Updating ASFEnhance plugin...
> 
> but after restart it's v2.2.4.0 again
> 
> 2024-10-07 22:18:30|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() Found ASFEnhance plugin update from version 2.2.4.0 to 2.2.4.2... 2024-10-07 22:18:30|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() New ASFEnhance plugin version is available! Consider updating yourself!
> 
> ![image](https://private-user-images.githubusercontent.com/28785698/374300682-8a2817a5-f47c-401c-9c87-8472d62c7662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTIxNDQsIm5iZiI6MTcyODM1MTg0NCwicGF0aCI6Ii8yODc4NTY5OC8zNzQzMDA2ODItOGEyODE3YTUtZjQ3Yy00MDFjLTljODctODQ3MmQ2MmM3NjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAxNDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NDhiYjQ1NDM0MWRkZmI4MGFmZWIzNzZmMmVlMGUzZDlmZDI0NjExZTU0NzNiOTE5MmQwNWE1ZTc2NTY1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2R5VirBBvRMeMgV9NpJRl4LtNv_ZUQGnWr7HIUXIzY8)
> 
> Something's wrong. It should update to v2.2.4.2, because my ASF is v6.0.8.3 and is Pre-Release, right?

just for testing github action, no need to upgrade this release

**Comment by chr233** [comment]
Now ASFEnhance will publish with all supported language together (english and russion), what's way to name plugin's resource libraries?

1. .net's default way
![image](https://github.com/user-attachments/assets/1acf2168-36c5-42a9-9dd3-605a1f12af9f)

2. named manually
![image](https://github.com/user-attachments/assets/6c7b5d47-fc52-49aa-a63b-7818e91a0120)

**Comment by Botan626** [comment]
> just for testing github action, no need to upgrade this release

I know it's was for testing, but still it had to update to v2.2.4.2 if I'm correct, since both ASF and ASFE were pre-release.

-

ASFE was successfully updated to v2.2.5.0 now.

**Comment by Botan626** [comment]
Another thing is `PV` command output.

![image](https://github.com/user-attachments/assets/dfe8c831-1cbb-42a5-a0b9-cd61acd02bac)

this line 
`Current version: 2.2.5.0 New version: 2.2.4.0` 
could be like
`Installed version: 2.2.5.0 Stable version: 2.2.4.0` 

in order to differentiate between pre-release and stable ASFE versions.

**Comment by chr233** [comment]
> ```
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdateASF() 正在检查新版本……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdateASF() 当前版本：6.1.1.3 | 最新版本：6.1.1.3
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugins() 正在检查插件更新……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugin() 正在检查插件 ASFEnhance 的更新……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugin() 正在检查插件 FreePackages 的更新……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugin() 正在检查插件 ASFFreeGamesPlugin 的更新……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugin() 正在检查插件 BoosterManager 的更新……
> 2025-01-02 17:35:10|dotnet-6036|INFO|ASF|UpdatePlugin() 正在检查插件 ASF Multiple Proxy 的更新……
> 2025-01-02 17:35:11|dotnet-6036|INFO|ASF|GetTargetReleaseURL() 插件 BoosterManager 没有可用的更新：2.10.2.1 ≥ 2.10.2.1。
> 2025-01-02 17:35:11|dotnet-6036|INFO|ASF|GetTargetReleaseURL() 插件 FreePackages 没有可用的更新：1.5.4.5 ≥ 1.5.4.5。
> 2025-01-02 17:35:11|dotnet-6036|INFO|ASF|GetTargetReleaseURL() 插件 ASF Multiple Proxy 没有可用的更新：1.1.0.0 ≥ 1.1.0.0。
> 2025-01-02 17:35:11|dotnet-6036|INFO|ASF|GetTargetReleaseURL() 找到插件 ASFEnhance 从版本 2.3.2.1 到 2.3.3.0 的更新……
> 2025-01-02 17:35:11|dotnet-6036|INFO|ASF|UpdatePlugin() 正在更新插件 ASFEnhance……
> 2025-01-02 17:35:12|dotnet-6036|DEBUG|ASF|OnProgressChanged() ASFEnhance 0%...
> 2025-01-02 17:35:13|dotnet-6036|DEBUG|ASF|OnProgressChanged() ASFEnhance 100%...
> 2025-01-02 17:35:13|dotnet-6036|INFO|ASF|UpdatePlugin() 修补 ASF 文件……
> 2025-01-02 17:35:13|dotnet-6036|INFO|ASF|UpdatePlugin() 更新插件 ASFEnhance 成功，更改将会在 ASF 下次运行时生效。
> 2025-01-02 17:35:13|dotnet-6036|INFO|ASF|RestartOrExit() 正在重新启动……
> 2025-01-02 17:35:18|dotnet-6036|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
> 2025-01-02 17:35:18|dotnet-6036|INFO|XXXXXXXX|Stop() 正在停止……
> 2025-01-02 17:35:18|dotnet-6036|INFO|XXXXXXXX|OnDisconnected() 已从 Steam 断开连接！
> 2025-01-02 17:35:20|dotnet-4172|INFO|ASF|InitCore() ArchiSteamFarm V6.1.1.3 (generic/fcd8b16d1b4e4ce086e8b490f76d614f | .NET 9.0.0; win-x64; Microsoft Windows 10.0.26100) in [C:\Users\X\tools\tools\ASF\core]
> 2025-01-02 17:35:20|dotnet-4172|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
> 2025-01-02 17:35:21|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.dll 无效！
> 2025-01-02 17:35:21|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance, Version=2.3.2.1, Culture=neutral, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> 2025-01-02 17:35:21|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.resources\en-US.dll 无效！
> 2025-01-02 17:35:21|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance.resources, Version=2.3.2.1, Culture=en-US, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> 2025-01-02 17:35:21|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.resources\ru-RU.dll 无效！
> 2025-01-02 17:35:21|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance.resources, Version=2.3.2.1, Culture=ru-RU, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在初始化 Plugins……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 ItemsMatcherPlugin V6.1.1.3……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() ItemsMatcherPlugin 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 MobileAuthenticatorPlugin V6.1.1.3……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() MobileAuthenticatorPlugin 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 SteamTokenDumperPlugin V6.1.1.3……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() SteamTokenDumperPlugin 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 ASFEnhance V2.3.3.0……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() ASFEnhance 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 ASF Achievemenevement Manager Ex V1.1.3.0……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() 插件作者: Rudokhvist, Chr_, 联系方式: chr@chrxw.com
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() 爱发电: https://afdian.net/@chr233
> 2025-01-02 17:35:21|dotnet-4172|DEBUG|ASF|OnLoaded() ASFEBridge 注册成功
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() ASF Achievemenevement Manager Ex 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 ASFFreeGamesPlugin V1.8.1.0……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() Loaded ASFFreeGamesPlugin
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() ASFFreeGamesPlugin 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 ASF Multiple Proxy V1.1.0.0……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() 插件作者: Chr_, 联系方式: chr@chrxw.com
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() 爱发电: https://afdian.net/@chr233
> 2025-01-02 17:35:21|dotnet-4172|DEBUG|ASF|OnLoaded() ASFEBridge 注册成功
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() ASF Multiple Proxy 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 BoosterManager V2.10.2.1……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() BoosterManager ASF Plugin by Citrinate
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() BoosterManager 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 正在加载 FreePackages V1.5.4.5……
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|OnLoaded() Free Packages ASF Plugin by Citrinate
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() FreePackages 加载成功！
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 您已将一个或多个自定义插件加载到 ASF 中。由于我们无法为修改过的程序提供支持，所以如果您遇到任何问题，请咨询相应插件的开发者。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 插件 ASFEnhance/ASFEnhance 已被注册并启用自动更新。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 插件 ASFFreeGamesPlugin/ASFFreeGames 已被注册并启用自动更新。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 插件 ASF Multiple Proxy/ASFMultipleProxy 已被注册并启用自动更新。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 插件 BoosterManager/BoosterManager 已被注册并启用自动更新。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|InitPlugins() 插件 FreePackages/FreePackages 已被注册并启用自动更新。
> 2025-01-02 17:35:21|dotnet-4172|WARN|ASF|InitPlugins() 自定义插件已被注册自动更新。ASF 团队提醒您，为了您的安全，您只应该为 信任来源启用自动更新，如果您不想这样做，则应该在 ASF 全局配置中禁用插件更新。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|UpdateAndRestart() ASF 将每隔 1 天自动检查新版本。
> 2025-01-02 17:35:21|dotnet-4172|INFO|ASF|UpdateASF() 正在检查新版本……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdateASF() 当前版本：6.1.1.3 | 最新版本：6.1.1.3
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugins() 正在检查插件更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugin() 正在检查插件 FreePackages 的更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugin() 正在检查插件 ASFFreeGamesPlugin 的更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugin() 正在检查插件 ASFEnhance 的更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdateCleanup() 正在清理更新后过时的文件……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugin() 正在检查插件 BoosterManager 的更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|UpdatePlugin() 正在检查插件 ASF Multiple Proxy 的更新……
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|GetTargetReleaseURL() 插件 FreePackages 没有可用的更新：1.5.4.5 ≥ 1.5.4.5。
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|GetTargetReleaseURL() 插件 ASF Multiple Proxy 没有可用的更新：1.1.0.0 ≥ 1.1.0.0。
> 2025-01-02 17:35:22|dotnet-4172|INFO|ASF|GetTargetReleaseURL() 插件 BoosterManager 没有可用的更新：2.10.2.1 ≥ 2.10.2.1。
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|UpdateCleanup() 完成！
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|GetTargetReleaseURL() 插件 ASFEnhance 没有可用的更新：2.3.3.0 ≥ 2.3.3.0。
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|OnASFInit() 尚未配置多重代理, 请设置 ASFEnhance.MultWebProxy
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|OnASFInit()
> ==========================================================================
>  █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
> ██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
> ███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗
> ██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝
> ██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
> ╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
> ==========================================================================
> ASFEnhance 版本 2.3.3.0
> 插件作者: Chr_, 联系方式: chr@chrxw.com
> 爱发电: https://afdian.com/@chr233
> ==========================================================================
> 已加载 2 个外部模块
> 
> 1: [AAM] ASF Achievemenevement Manager Ex 1.1.3.0
> 2: [AMP] ASF Multiple Proxy        1.1.0.0
> ==========================================================================
> 
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|Load() 正在加载 STD 全局缓存……
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|Load() 正在验证 STD 全局缓存完整性……
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|OnASFInit() 按照您的配置，SteamTokenDumperPlugin 当前被禁用。如果您愿意帮助 SteamDB 提交数据，请查看我们的 Wiki。
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|StartInteractiveConsole() 交互式控制台已启用，输入 c 以进入命令模式。
> 2025-01-02 17:35:25|dotnet-4172|INFO|ASF|Start() 正在启动 IPC 服务……
> 2025-01-02 17:35:25|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.dll 无效！
> 2025-01-02 17:35:25|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance, Version=2.3.2.1, Culture=neutral, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> 2025-01-02 17:35:25|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.resources\en-US.dll 无效！
> 2025-01-02 17:35:25|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance.resources, Version=2.3.2.1, Culture=en-US, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> 2025-01-02 17:35:25|dotnet-4172|ERROR|ASF|LoadAssembliesFrom() C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.resources\ru-RU.dll 无效！
> 2025-01-02 17:35:25|dotnet-4172|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: Could not load file or assembly 'ASFEnhance.resources, Version=2.3.2.1, Culture=ru-RU, PublicKeyToken=null'. Assembly with same name is already loaded
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
> ```

delete C:\Users\p\tools\tools\ASF\core\plugins\ASFEnhance\ASFEnhance.resources\ folder and replace with the release one
