### ISSUE TITLE
Licenses commands don't work

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#329]
ASF 6.0.8.5 - win-x64 + ASFEnhance 2.2.5.0

for
FREELICENSES 
LICENSES 
REMOVELICENSES 
commands output is this:
```
<ASFE> Missing Method Exception Detected, Use ASF-generic version may help
检测到 Missing Method Exception 错误, 换成 ASF-generic 版本可能可以修正
==========================================================================
   at ASFEnhance.Account.HtmlParser.ParseLincensesPage(HtmlDocumentResponse response)
   at ASFEnhance.Account.WebRequest.GetOwnedLicenses(Bot bot)
   at ASFEnhance.Account.Command.ResponseGetAccountLicenses(Bot bot, Boolean onlyFreelicense)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Account.Command.ResponseGetAccountLicenses(String botNames, Boolean onlyFreelicense)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
```

and for REMOVEDEMOS command output is  `Unknown command!`

**Comment by chr233** [comment]
use ASF-generic will fix
