### ISSUE TITLE
使用APIKEY 指令时报错

### ISSUE THREAD

**Issue by TheZafkiel** [chr233/ASFEnhance#93]
**Describe the bug / Bug 描述**
Describe what the bug is
简单描述一下是什么 bug

使用APIKEY 指令时报错

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

>
APIKEY ***
<
ASFenhance 遇到错误, 日志如下
==========================================
 - 原始消息: APIKEY ***
 - Access: Owner
 - ASF 版本: 5.4.3.2
 - 插件版本: 1.7.17.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": true,
  "DisabledCmds": [],
  "Address": null,
  "Addresses": []
}
==========================================
 - 错误类型: System.MissingMethodException
 - 错误消息: Method not found: 'System.Threading.Tasks.Task`1<System.ValueTuple`2<Boolean,!0>> ArchiSteamFarm.Helpers.ArchiCacheable`1.GetValue(EFallback<!0>)'.
   at ASFEnhance.DevFeature.Command.ResponseGetAPIKey(Bot bot)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFEnhance.DevFeature.Command.ResponseGetAPIKey(Bot bot)
   at ASFEnhance.DevFeature.Command.<>c__DisplayClass3_0.<ResponseGetAPIKey>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.DevFeature.Command.ResponseGetAPIKey(String botNames)
   at ASFEnhance.ASFEnhance.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)

**Comment by chr233** [comment]
收到，有空修复

**Comment by chr233** [comment]
貌似是ASF版本太高导致的，在ASF5.4.2.13下正常，等5.4.3.x出正式版了会跟进的

**Comment by TheZafkiel** [comment]
好嘞大佬辛苦~_(:з」∠)_
顺便想问下大佬知道怎么关闭asf的自动更新嘛.. 用5.4.2.13一直要自动更新.
![image](https://user-images.githubusercontent.com/61747242/228449566-f8d92507-4898-45c0-bc9d-f5f36925502d.png)

**Comment by chr233** [comment]
ASF 版本已跟进，使用1.7.19.1即可
